### PR TITLE
#117 add podspec dependency version constraints

### PR DESCRIPTION
**Pull request by dustin-graham**
Without version constraints, the underlying ios dependencies can update to
unsupported versions at any time. On 8/11/21 they did just that.
TextRecognition was bumped to 1.4.0 which happened to change the
MLKitTextRecognition.h header so that it no longer includes several necessary
imports. Version constraints should be explicitly made in this library's
podspec so that functionality can be guaranteed.

### CODE REVIEW

**Review by fbernaly — APPROVED** [review]

**Comment by dustin-graham** [comment]
@bharat-biradar , Thank you for merging this. Can we make a new release with these changes?

**Comment by bharat-biradar** [comment]
@dustin-graham I'll release a patch version, `.7.1` by tomorrow, thanks for reminding and for the PR.

**Comment by officialFlutterDeveloper** [comment]
@bharat-biradar @dustin-graham  but 0.7.1 still throws the text recognition error even the 0.7.2 throws the error :((((((

**Comment by NickDatLe** [comment]
I'm on version 0.7.3 and it still fails.

**Pull request merged**
