### PR TITLE
Add live feed example for label detection

### PR DESCRIPTION
**Pull request by fbernaly**
* Add camera plugin to get live feed.
* Select live feed or still image

### CODE REVIEW

**Comment by fbernaly** [comment]
@bharat-biradar: I was playing with your plugin and want to add live feed to the detectors. I started with the Image labeler. Look at the code and let me know if that is okay, I would like to contribute more. 
I also noticed that Face detector is not added, I am interested in using face detector for my aplication, and I would like to add it.

**Comment by bharat-biradar** [comment]
@fbernaly Thanks for opening the PR. I will check and get back to you shortly.

**Comment by bharat-biradar** [comment]
@fbernaly Everything seems to be working fine. Can you handle the problem pointed out by the analyzer before merging the changes? If you are busy please let me know and I can do it.
Also please go ahead and implement the face detector it would be a huge help.

**Comment by fbernaly** [comment]
@bharat-biradar: fixed

**Review by bharat-biradar — APPROVED** [review]

**Pull request merged**
