### PR TITLE
Add Face Detection for iOS 

### PR DESCRIPTION
**Pull request by fbernaly**
* FaceProcessor.m
* Obj-c category: MLKVisionImage(FlutterPlugin)
* Update pod dependencies for iOS
* Update InputImageFormat
* Update README

### CODE REVIEW

**Comment by fbernaly** [comment]
@bharat-biradar: I added Face detection for iOS. Let me know your comments.

**Comment by bharat-biradar** [comment]
@fbernaly Thanks for adding this. Can you give me at least a day to through this, there are a lot of changes.
I did not notice it in the last PR, but you changed have changed the links for screenshots. I was not using a relative path to screenshots as they would not show up on pub.dev page. Can you change that for now?

**Comment by fbernaly** [comment]
@bharat-biradar did not know that, I will change that and include it in this PR

**Comment by fbernaly** [comment]
@bharat-biradar: done

**Review by cngeru — COMMENTED** [review]
Looks ok

**Review by cngeru — APPROVED** [review]
Looks good to me

**Comment by fbernaly** [comment]
I have ImageLabeler in iOS as well, but that will come in another PR

**Comment by bharat-biradar** [comment]
@fbernaly Sorry for taking this long. I actually use windows and use flutlab and appetize to run an IOS build but that doesn't seem to work for plugins and I had spent more than half a day just to run the build. Everything looks good to me. Thanks again.

**Review by bharat-biradar — APPROVED** [review]

**Comment by fbernaly** [comment]
@bharat-biradar: I noticed the overflow and fixed it in my upcoming PR.

**Comment by bharat-biradar** [comment]
@fbernaly thanks a lot. Is there any way you could send me the IOS debug build if possible for next pr. I'm asking because it will make it faster to check.

**Comment by fbernaly** [comment]
Sure, I will do that. I will signed it with my personal Apple Developer Account, but for that I will need the UDID of the device you intend to install the app. Apple is not that flexible as Android when it comes to distributing beta/debug builds. But sharing your UDID here is not secure, I think we need to move this conversation to emails.

**Comment by fbernaly** [comment]
@bharat-biradar:

 Here are the instructions to get the UDID:

Open this link in safari in your iphone
https://webapp.diawi.com/device
Tap Start > Allow installation > follow directions and at the end copy it.

If you go to my GitHub profile you can find a link to my LinkedIn profile in send a message with the UDID.

**Pull request merged**
