### PR TITLE
Add headEulerAngleX

### PR DESCRIPTION
**Pull request by jdiazgon55**
Related to #183. This PR adds the possibility to get the `headEulerAngleX` from the face detection. Works in iOS and Android

### CODE REVIEW

**Review by fbernaly — APPROVED** [review]

**Comment by fbernaly** [comment]
@jdiazgon55: PR LGTM, just run `flutter analyze .` and resolve the issues.

**Comment by fbernaly** [comment]
@jdiazgon55: are you still interested in getting this PR merged? we are about to push more changes to split the plugin in multiple plugins by feature, and I would like to include yours in the current code base before having merging conflicts.

**Comment by jdiazgon55** [comment]
Sure I would like to, but I am on a business trip till Tuesday. I just need some time

**Comment by fbernaly** [comment]
ok, we are going to wait till Tuesday/Wednesday

**Comment by jdiazgon55** [comment]
Hi @fbernaly, I have fixed the `flutter analyze .` issues, however it seems that you already did that on a previous commit. So I guess it is now ready to be merged:

image

**Comment by fbernaly** [comment]
@jdiazgon55: Thanks for the contribution.

**Pull request merged**
