### PR TITLE
fix: modifed face_detector import class.

### LINKED ISSUE #363: Error: 'Rect' isn't a type - google_mlkit_face_detection
when switch into google_mlkit_face_detection version 0.4.0 to 0.5.0.
I got a error.

```
Error: 'Rect' isn't a type.
../…/src/face_detector.dart:103
  final Rect boundingBox;
        ^^^^
```

`flutter doctor -v`
```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.2130], locale en-US)
    • Flutter version 3.0.4 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
```

I found a solution, upgrade **flutter verion to 3.3.7** now it works for this version.

### PR DESCRIPTION
**Pull request by nomunomu0504**
close #363 

Now, The plugin cause below error.
```
packages/google_mlkit_face_detection/lib/src/face_detector.dart:103:9: Error: 'Rect' isn't a type.
      final Rect boundingBox;
            ^^^^
```

So I added the `package:flutter/material.dart` import statement with this modification and changed the "package:flutter/services.dart" to be used only with methodCahnnel.

### CODE REVIEW

**Comment by fbernaly** [comment]
@nomunomu0504 : what is this fix doing? could you provide more detail?

**Comment by nomunomu0504** [comment]
@fbernaly 
Thanks review.
I added more information of this PR.

**Comment by nomunomu0504** [comment]
My guess is that there are other packages other than face_detect that need to be modified in a similar way.
This time the modification is limited to face_detect.

**Comment by nomunomu0504** [comment]
@fbernaly 
Thank you. I will try to find time to fix the other issues.

**Review by fbernaly — APPROVED** [review]

**Pull request merged**
