### PR TITLE
chore: Upgrade iOS and Android dependencies

### PR DESCRIPTION
**Pull request by mitch2na**
Fixes https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/408

Dependency issue between Firebase and MLKitVision
https://issuetracker.google.com/issues/254418199

### CODE REVIEW

**Comment by fbernaly** [comment]
LGTM

**Comment by fbernaly** [comment]
I will merge today, but I will release a new version on Monday.

**Review by fbernaly — APPROVED** [review]

**Comment by cuonghoang96** [comment]
please update @fbernaly 🙏

**Comment by fbernaly** [comment]
done: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/432

**Pull request merged**
