### PR TITLE
mlkit language identification for iOS

### PR DESCRIPTION
**Pull request by nachtmaar**
This PRimplements the language identification feature of mlkit as described in issue #129.

ToDo:

- [x] import code from own plugin implementation
- [x] compile successful
- [x] use confidence value
- [x] implement identifyLanguageForText
- [x] test feature via example

### CODE REVIEW

**Comment by nachtmaar** [comment]
@fbernaly The PR is ready for a review. Please let me know later if you want me to squash the commits.

**Comment by nachtmaar** [comment]
@fbernaly I just checked the android code of the language identification. I saw that the case of an undetermined language is not handled as an error (as in my implementation). I think we should unify both implementations.

What is your take? And which option do you prefer? If we just pass the "und" language tag on to the dart code, we should add some documentation imho telling the use to take care of this. At least give the user a hint.

**Comment by fbernaly** [comment]
@nachtmaar: could you change the Android code to handle the error as you are doing in iOS. Also you need to add that to the readme

**Comment by nachtmaar** [comment]
@fbernaly Sure I can do so. However I am not sure about how to proceed and need your opinion.

The reason is the following: If we decide that a not detected language is an error, then I feel we need to give the user a way to separate that from an error which is caused by an implementation bug.

At the moment there is only a `PlatformException`. There is no other exception class.

```dart
      try {
        List<IdentifiedLanguage> languages =
            await languageIdentifier.identifyPossibleLanguages(block.text);
        print("block $i: ${block.text} => $languages");
      } on PlatformException {
        print("no language identified for: ${block.text}");
      }
```

There are now 2 ways I can image of how to separate the errors:

**Option 1** (using the PlatformException `code`):

```dart
try {
  List<IdentifiedLanguage> languages =
      await languageIdentifier.identifyPossibleLanguages(block.text);
  blockLanguages[i] = languages;
  print("block $i: ${block.text} => $languages");
} on PlatformException catch (e) {
  if (e.code == languageIdentifier.errorCodeNoLanguageIdentified) { // error code exposed to user as part of API
    print("no language identified for: ${block.text}");
  }
```

**Option 2** (using custom `error classes`, LanguageDetectionError in this case):

```dart
      try {
        List<IdentifiedLanguage> languages =
            await languageIdentifier.identifyPossibleLanguages(block.text);
        print("block $i: ${block.text} => $languages");
      } on LanguageDetectionError { // <------- custom error class
        print("no language identified for: ${block.text}");
      }
      on PlatformException {
        print("error in plugin while identifying language of: ${block.text}");
      }
```

Before I proceed we should align on the two options.

Option 1 is:
+ easy to implement
- but means we need to expose the possible error codes to the user so that they can rely on them. In the excample `errorCodeNoLanguageIdentified` is a instance variable of `LanguageIdentifier`

Option 2:
+ is more natural to use since it can be used in the `on clause` in try/catch
- disadvantage: I don"t know how to implement that: it seems only the [GoogleMlKitPlugin](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/pubspec.yaml#L33) class is exposed to the user. So how can a custom exception class be exposed to the user ?
 
I don"t know how other plugins are doing this, but I quickly checked [flutterfire](https://github.com/FirebaseExtended/flutterfire/blob/1f8d79a3ee2ab6e5a73cd57d1ce164bccfe14879/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart) and they have a custom error class.

What is your take on this? I wanted to bring this up because it influences the API design of the plugin.

I personally prefer option 2, but would start now with option 1 as we should keep it simple for now.

**Comment by fbernaly** [comment]
@nachtmaar : I agree with you that option 2 would be more elegant, but let's keep it simple and go with option 1 for now. We can improve/refactor this later. Go ahead and implement the solution using option 1.

**Comment by nachtmaar** [comment]
@fbernaly Everything is implemented. I tested the android and the iOS example. Please have a look now :)

**Review by fbernaly — APPROVED** [review]

**Pull request merged**
