### PR TITLE
Update AGP to 7.2.1

### PR DESCRIPTION
**Pull request by jaredsburrows**
@bharat-biradar 

Updated:
 - AGP: `7.2.1`
 - Gradle: `7.4.2`

Tested via:
```
cd packages/google_ml_kit/example/
flutter build apk --debug
flutter run
```

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@bharat-biradar I ma not sure why this is failing. Can you allow contributors to run the CI?

**Comment by bharat-biradar** [comment]
@jaredsburrows  I changed the permissions I think you should be able to run now. Please check.

**Comment by jaredsburrows** [comment]
@jaredsburrows @fbernaly CI passed, should be good to go :)

**Comment by fbernaly** [comment]
@jaredsburrows: when I run the example Flutter app from the main project it is working, it compiles and runs in the Android device, I am getting a bunch of lint warnings but it builds the apk at the end:

```
Note: /Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/google_mlkit_commons-0.2.0/android/src/main/java/com/google_mlkit_commons/InputImageConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:154: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:158: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:162: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:166: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:170: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:174: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
                                 ^
/Users/fbernaly/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+21/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:178: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
                                 ^
7 warnings
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_digital_ink_recognition/android/src/main/java/com/google_mlkit_digital_ink_recognition/DigitalInkRecognizer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_entity_extraction/android/src/main/java/com/google_mlkit_entity_extraction/EntityExtractor.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_face_detection/android/src/main/java/com/google_mlkit_face_detection/FaceDetector.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_object_detection/android/src/main/java/com/google_mlkit_object_detection/ObjectDetector.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_pose_detection/android/src/main/java/com/google_mlkit_pose_detection/PoseDetector.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_selfie_segmentation/android/src/main/java/com/google_mlkit_selfie_segmentation/SelfieSegmenter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fbernaly/workspace/Google-Ml-Kit-plugin/packages/google_mlkit_text_recognition/android/src/main/java/com/google_mlkit_text_recognition/TextRecognizer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
```

But when I try to open the android project: Google-Ml-Kit-plugin/packages/google_ml_kit/example/android as an Android Project, it is not building, and it was before. I am getting this error, Gradle project sync is failing:

```
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.2.1 or newer.
```

How can I fix that?

**Comment by jaredsburrows** [comment]
For the warnings:
 - Camera needs to be updated to `0.9.8` - see https://pub.dev/packages/camera

For the IDE error, you need to upgrade your IDE(Android Studio) to use the latest Android Gradle Plugin.

**Comment by fbernaly** [comment]
@jaredsburrows : ok, after updating to Chipmunk, and some plugin it worked.

**Review by fbernaly — APPROVED** [review]

**Pull request merged**
