### PR TITLE
fix: missing "id" field when calling identifyLanguage (#358)

### PR DESCRIPTION
**Pull request by huycn**

### CODE REVIEW

**Review by fbernaly — APPROVED** [review]

**Comment by fbernaly** [comment]
LGTM, but first fix what the checks require before I can merge.

**Comment by fbernaly** [comment]
Look at the details of the check to see why it is failing and fix it, then I will merge.

**Comment by huycn** [comment]
Sorry, I give up. I cannot understand why just bay adding one entry to a map with the exactly spacing like the line below would violate any formatting rules out there.

You can close this PR and fix it using another commit (just one line to copy). I no longer use this method, and I don't care my reputation.

By the way, thank you for this awesome repo. This and translation module is very useful for us.

**Comment by fbernaly** [comment]
@huycn : Thanks for your contribution.

**Pull request closed without merging**
